# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/

image: node:12.14.1-slim

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - server/node_modules/

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

test:
  stage: test
  script:
    - cd server
    - echo "{\"client_id\":\"$CLIENT_ID\", \"client_secret\":\"$CLIENT_SECRET\"}"
    - echo "{\"client_id\":\"$CLIENT_ID\", \"client_secret\":\"$CLIENT_SECRET\"}" > authentication.json
    - npm install
    - npx jest

deploy:
  stage: deploy
  script:
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh spotifymoodtracker@35.230.144.118 "cd web-tech && docker-compose stop && git checkout staging && git pull origin staging && exit"
    - ssh spotifymoodtracker@35.230.144.118 "cd web-tech/server && npm i && cd ../db_update_service && npm i && exit"
    - ssh spotifymoodtracker@35.230.144.118 "cd web-tech && docker-compose build --no-cache && docker-compose -f docker-compose-staging.yml up && exit"
  only: 
    - staging