# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/

image: node:12.14.1-slim

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - api/node_modules/
    - frontend/node_modules
    - db_update_service/node_modules
    - https-redirector/node_modules


before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

test:
  stage: test
  script:
    - cd api
    - echo "{\"client_id\":\"$CLIENT_ID\", \"client_secret\":\"$CLIENT_SECRET\"}"
    - echo "{\"client_id\":\"$CLIENT_ID\", \"client_secret\":\"$CLIENT_SECRET\"}" > authentication.json
    - echo "{\"refresh_token\":\"$REFRESH_TOKEN\"}" > tokens.json
    - npm install
    - npx jest

deploy:
  stage: deploy
  script:
    - echo "{\"client_id\":\"$CLIENT_ID\", \"client_secret\":\"$CLIENT_SECRET\"}" > authentication.json
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh spotifymoodtracker@35.230.138.23 "cd web-tech && docker-compose stop && git checkout staging && git stash && git pull origin staging && exit"
    - scp authentication.json spotifymoodtracker@35.230.138.23:~/web-tech/server
    - ssh spotifymoodtracker@35.230.138.23 "cd web-tech && docker-compose build --no-cache && docker-compose -f docker-compose-staging.yml up -d && exit"
  only: 
    - staging