version: "3.7"

services:

    backend:
        build: ./server
        volumes:
          - ./server:/server
        command: npm run dev
        environment: 
          - NODE_ENV=test
          - URL=http://localhost:5000
          - PORT=5000
        ports:
          - '5000:5000'


    frontend:
        build: ./frontend
        command: npm run serve -- --port 80 --host 0.0.0.0
        volumes:
          - ./frontend:/frontend
        ports:
          - '80:80'
        depends_on: 
          - backend
        network_mode: host

    db_update_service:
        build: ./db_update_service
        volumes:
          - ./db_update_service:/db_update_service
        command: npm run start
        environment:
          - NODE_ENV=test
          - URL=http://localhost:5000
          - PORT=5000
        depends_on:
          - backend
