version: '3.7'

services:
    backend:
        build: ./server
        command: npm run start
        environment:
            - NODE_ENV=staging
            - URL=https://35.230.138.23
            - PORT=5000
        volumes:
            - ./server/sqlite-db:/server/sqlite-db
        ports:
            - '5000:5000'

    frontend:
        build: ./frontend
        command: npm run serve -- --port 443  --host 0.0.0.0
        ports:
            - '443:443'
        environment: 
            - VUE_APP_URL=https://35.230.138.23:5000 
        depends_on:
            - backend
        network_mode: host

    db_update_service:
        build: ./db_update_service
        command: npm run start
        environment:
            - NODE_ENV=staging
            - URL=https://35.230.138.23
            - PORT=5000
        depends_on:
            - backend
