version: "3.7"

services:

    backend:
        build: ./server
        command: npm run start
        environment: 
            - DEBUG=0
        ports:
            - '80:80'

    db_update_service:
        build: ./db_update_service
        command: npm run start
        environment: 
            - DEBUG=0
        depends_on:
          - backend
