version: '3.7'

services:
    api:
        build: ./api
        command: npm run start
        environment:
            - NODE_ENV=staging
            - URL=https://35.230.138.23
            - PORT=5000
        volumes:
            - ./api/sqlite-db:/api/sqlite-db
        ports:
            - '5000:5000'

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.staging
        command: npm run serve
            - '443:443'
        environment: 
            - VUE_APP_URL=https://35.230.138.23:5000 
        depends_on:
            - api
        network_mode: host

    db_update_service:
        build: ./db_update_service
        command: npm run start
        environment:
            - URL=https://35.230.138.23
            - PORT=5000
        depends_on:
            - api
