version: "3.7"

services:

    # db:
    #     image: mysql:5.7
    #     restart: always
    #     command: --disable-partition-engine-check
    #     environment:
    #         MYSQL_DATABASE: 'db'
    #         # So you don't have to use root, but you can if you like
    #         MYSQL_USER: 'admin'
    #         # You can use whatever password you like
    #         MYSQL_PASSWORD: 'root'
    #         # Password for root access
    #         MYSQL_ROOT_PASSWORD: 'root'
    #     volumes:
    #         - ./db-init:/docker-entrypoint-initdb.d
    #         - ./db:/var/lib/mysql
    #     ports:
    #         - '3306:3306'
    #     expose:
    #         - '3306'

    backend:
        build: ./server
        volumes:
            - ./server:/app
        command: npm run test
        ports:
            - '5000:5000'
        # depends_on:
        #     - db

    db_update_service:
        build: ./db_update_service
        volumes:
          - ./db_update_service:/app
        command: npm run test
        depends_on:
        #   - db
          - backend
