version: "3.7"

services:

    backend:
        build: ./server
        command: npm run start
        ports:
            - '5000:5000'

    db_update_service:
        build: ./db_update_service
        command: npm run start
        depends_on:
          - backend
