version: '3.7'

services:
    api:
        build: ./api
        volumes:
            - ./api:/api

        command: npm run dev
        environment:
            - NODE_ENV=test
            - URL=https://localhost:5000 
            - PORT=5000
        ports:
            - '5000:5000'

    frontend:
        build: ./frontend
        command: npm run serve
        volumes:
            - ./frontend:/frontend

        environment: 
            - VUE_APP_URL=https://localhost:5000 
        depends_on:
            - api
        network_mode: host

    https-redirector:
        build: ./https-redirector
        volumes:
            - ./https-redirector:/https-redirector
        command: node redirector.js
        depends_on:
            - api
        network_mode: host

    db_update_service:
        build: ./db_update_service
        volumes:
            - ./db_update_service:/db_update_service
        command: npm run start
        environment:
            - NODE_ENV=test
            - URL=https://localhost:5000
            - PORT=5000
        depends_on:
            - api
