version: "3.7"

services:

    backend:
        build: ./server
        volumes:
            - ./server:/app
        command: npm run dev
        ports:
            - '5000:5000'

    db_update_service:
        build: ./db_update_service
        volumes:
          - ./db_update_service:/app
        command: npm run dev
        depends_on:
          - backend
