version: "3.7"

services:

    backend:
        build: ./server
        volumes:
          - ./server:/app
        command: npm run dev
        environment: 
          - NODE_ENV=test
          - URL=http://localhost:5000
          - PORT=5000
        ports:
          - '5000:5000'

    db_update_service:
        build: ./db_update_service
        volumes:
          - ./db_update_service:/app
        command: npm run start
        environment:
          - NODE_ENV=test
          - URL=http://localhost:5000
          - PORT=5000
        depends_on:
          - backend
